import Head from 'next/head'
import React from 'react'
import { Grid, Divider } from '@material-ui/core'
import Navbar from '../components/Navbar'
import LinkedInIcon from '@material-ui/icons/LinkedIn';
import GitHubIcon from '@material-ui/icons/GitHub';
import InstagramIcon from '@material-ui/icons/Instagram';
import Link from 'next/link'

export default function Disclaimer() {

  return (
    <div>
      <Head>
        <title>Jakarta Hospital Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Hospital.svg" />
      </Head>

      <main className='main-container'>
        <Navbar />
        <Grid container className='primal-container' direction='column'>
          <h1 className='rokkit disclaimer-title'>Disclaimer</h1>
          <p className='rokkit disclaimer-point'>Data yang terdapat di website ini merupakan data yang diambil dari <a href='https://github.com/satyawikananda/rs-bed-covid-indo-api/' target='_blank' rel="noreferrer" style={{ textDecoration: 'underline' }}>satyawikananda/rs-bed-covid-indo-api</a>.</p>
          <p className='rokkit disclaimer-point'>Data diupdate secara berkala dan mungkin saja terjadi perbedaan antara data dengan kondisi rumah sakit yang sebenarnya.</p>
          <p className='rokkit disclaimer-point'>Peta yang ditampilkan mungkin saja tidak 100% akurat dengan lokasi rumah sakit yang sebenarnya.</p>
          <p className='rokkit disclaimer-point'>Website belum optimal untuk dibuka di perangkat mobile dan akan diupdate secara berkala.</p>
          <br/><br/><br className='sm-hide' />
          <p className='rokkit disclaimer-point'>Regards,</p><br/><br className='sm-hide' />
          <p className='rokkit disclaimer-point'>Aji Widhya Yudhanto</p>
          <div className='icon-container'>
            <a href='https://www.linkedin.com/in/aji-yudhanto-905ab0125/' target='_blank' rel="noreferrer">
              <LinkedInIcon className='sosmed-icon-big' />
            </a>
            <Divider orientation="vertical" flexItem className='icon-separator' />
            <a href='https://github.com/ajiyudhanto' target='_blank' rel="noreferrer">
              <GitHubIcon className='sosmed-icon-small' />
            </a>
            <Divider orientation="vertical" flexItem className='icon-separator' />
            <a href='https://www.instagram.com/awyudhanto/' target='_blank' rel="noreferrer">
              <InstagramIcon className='sosmed-icon-big' />
            </a>
          </div>
        </Grid>
      </main>

    </div>
  )
}