import Head from 'next/head'
import { useRouter } from 'next/router'
import Navbar from '../components/Navbar'
import Landing from '../components/Landing'
import { Grid, FormControl, InputLabel, NativeSelect } from '@material-ui/core'

export default function Home() {
  const router = useRouter()

  const handleChange = (event) => {
    router.push(`/${event.target.value}`)
  };

  return (
    <div>
      <Head>
        <title>Jakarta Hospital Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Hospital.svg" />
      </Head>

      <main className='main-container'>
        <Navbar />
        <Landing className='landing-svg' />
        <Grid container className='title-container' direction='column'>
          <h1 className='rokkit title-landing-page'>Ketersediaan Rumah Sakit Indonesia</h1>
          <h2 className='rokkit subtitle-landing-page'>data ini diambil dari <a href='https://github.com/satyawikananda/rs-bed-covid-indo-api/' target='_blank' style={{ textDecoration: 'underline' }}>satyawikananda/rs-bed-covid-indo-api</a></h2>
          <select
            value=''
            onChange={handleChange}
            className='native-selection rokkit'
          >
            <option value={''} className='select-option'>Data apa yang ingin Anda lihat?</option>
            <option value={'covid'} className='select-option'>Tempat tidur pasien covid</option>
            <option value={'non-covid'} className='select-option'>Tempat tidur pasien non-covid</option>
          </select>
        </Grid>
      </main>
    </div>
  )
}
