import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Landing from '../components/Landing'
import { Grid, FormControl, InputLabel, NativeSelect } from '@material-ui/core'

export default function Home() {

  const handleChange = (event) => {
    const name = event.target.name;
  };

  return (
    <div>
      <Head>
        <title>Jakarta Hospital Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>

      <main className='main-container'>
        <Navbar />
        <Landing className='landing-svg' />
        <Grid container className='title-container' direction='column'>
          <h1 className='rokkit title-landing-page'>Data Rumah Sakit di Jakarta</h1>
          <h2 className='rokkit subtitle-landing-page'>data ini diambil dari api.jakarta.go.id</h2>
            <select
              value=''
              onChange={handleChange}
              className='native-selection rokkit'
            >
              <option value={''} className='select-option'>Data apa yang ingin Anda lihat?</option>
              <option value={'RSU'} className='select-option'>Rumah Sakit Umum</option>
              <option value={'RSK'} className='select-option'>Rumah Sakit Khusus</option>
              <option value={'PS'} className='select-option'>Puskesmas</option>
            </select>
        </Grid>
      </main>
    </div>
  )
}
